### ISSUE TITLE
We need a config.gradle file for each service (cts, cc, etc.)

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cs2#59]
In our old sparqlcts, we had a config.gradle file, with a tokenmap for inserting values at build-time. We don't seem to have one now, unless (which is entirely possible) I am not seeing how and where this is done under the new integrated Gradle project.

I would like to be able to insert root-URLs, into the xslt skins, for navigation links. 

It would also be nice to be able to fire up SparqlCTS pointing at different Sparql endpoints. So we could have test-data in one endpoint, e.g. `.../fuseki/testCts/query`, which the integration and unit-tests would look at, _and_ which we could use when running sparqlCTS to feed cts-validator. But we could keep real data at `.../fuseki/cts/query` (_vel sim._), and start sparqlCts with a different, or default, config so it would point there.

**Comment by neelsmith** [comment]
We also want to be able to modify these settings without recompiling -- eg, toss a war into a servlet container, but modify settings. The proper way to do this is with either servlet context params or servlet init params.  sparqlcts now works this way:  for testing, appropriate values are set in the build file;  for use in a war, you set up web.xml in your container.  By default, the repo has a web.xml with approrpiate values for unmodified use in citevm. Closing -- we should apply the same method to all services
